package renderer

import (
	"fmt"
	"os"
	"strings"
	"time"
)

// UpdateIndex — output/README.md에 새 카드뉴스 링크 추가
func UpdateIndex(topic, cardFilename string) error {
	indexPath := "output/README.md"
	now := time.Now().Format("2006-01-02 15:04")

	// htmlpreview 링크 생성
	previewURL := fmt.Sprintf(
		"https://htmlpreview.github.io/?https://github.com/susooo/research-agent/blob/main/output/%s",
		cardFilename,
	)

	// 새 항목
	newRow := fmt.Sprintf("| %s | %s | [보기](%s) |\n",
		now,
		topic,
		previewURL,
	)

	// 기존 파일 읽기
	existing := ""
	if data, err := os.ReadFile(indexPath); err == nil {
		existing = string(data)
	}

	// 기존 파일 있으면 행만 추가
	if existing != "" && strings.Contains(existing, "| 날짜 |") {
		updated := strings.Replace(
			existing,
			"| --- | --- | --- |\n",
			"| --- | --- | --- |\n"+newRow,
			1,
		)
		return os.WriteFile(indexPath, []byte(updated), 0644)
	}

	// 새로 생성
	md := buildIndexMD(newRow)
	return os.WriteFile(indexPath, []byte(md), 0644)
}

func buildIndexMD(firstRow string) string {
	return fmt.Sprintf(`# 🔍 Research Agent — 리서치 목록

> AI Research Agent가 자동 생성한 리서치 카드뉴스 모음

---

## 카드뉴스 목록

| 날짜 | 주제 | 링크 |
| --- | --- | --- |
%s
---

*Generated by [Research Agent](../README.md)*
`, firstRow)
}